variable "cidr_block" {}
variable "vpc_name" {}
variable "created_by" {}
variable "env" {}
variable "region" {}
variable "pubSubnet1_cidr_block" {}
variable "pubSubnet1Az" {}
variable "pubSubnet2_cidr_block" {}
variable "pubSubnet2Az" {}
variable "pubSubnet3_cidr_block" {}
variable "pubSubnet3Az" {}
variable "pvtSubnet1_cidr_block" {}
variable "pvtSubnet2_cidr_block" {}
variable "pvtSubnet3_cidr_block" {}